### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by mcollina** [cemremengu/fastify-example-todo#1]
As titled

**Comment by cemremengu** [comment]
What's best place to wipe a database/collection after a test?

I am having trouble accessing `app.mongo` (undefined) inside tests or inside `helper.js` (although I expected to be able to access it)

https://github.com/cemremengu/fastify-example-todo/blob/123ecde904a6b7716c3342ce2ea564658f8fa470/test/helper.js#L26

**Comment by mcollina** [comment]
https://www.npmjs.com/package/mongo-clean :)

**Comment by cemremengu** [comment]
@mcollina could you give a quick look at #4 when you have time? I am specifically curious about the approach using https://github.com/cemremengu/fastify-example-todo/blob/f68450ca911253e769140ba26e0c2b205091ee10/test/helper.js#L37
