### ISSUE TITLE
Windows Install

### ISSUE THREAD

**Issue by johntom** [cemremengu/fastify-example-todo#10]
I've evaluated many frameworks to replace my trails/sails repos and have decided on Fastify. I'm looking for repo's to jumpstart my efforts and was hoping to view this todo app but locahost:300 displays {
statusCode: 404,
error: "Not Found",
message: "Not Found"
}
http://localhost:3000/api/todo/ displays
{
statusCode: 401,
error: "Unauthorized",
message: "No Authorization was found in request.headers"
}
If possible could you provide the steps required to run this example.
os: win10
node:10.15.3
npm: 6.4.1
mongodb: 4.0
Thanks,
John

**Comment by StarpTech** [comment]
Hi @johntom, please provide a proper issue description otherwise it will be ignored.

**Comment by johntom** [comment]
Sorry, I did realize I had started the thread and since provided details.

**Comment by johntom** [comment]
i tried to authenticate after creating user in todo/users and get token with post
http://localhost:3000/api/auth/token
body :{"username": "jrt", "password": "12345678"}

res
{
    "statusCode": 415,
    "code": "FST_ERR_CTP_INVALID_MEDIA_TYPE",
    "error": "Unsupported Media Type",
    "message": "FST_ERR_CTP_INVALID_MEDIA_TYPE: Unsupported Media Type: application/x-www-form-urlencoded"
}

**Comment by Eomm** [comment]
> Unsupported Media Type: application/x-www-form-urlencoded

This means that you are using a `content-type` header with a wrong value: it should be `application/json`

**Comment by johntom** [comment]
All working! Thanks
